CREATE DATABASE IF NOT EXISTS employee_db;
CREATE DATABASE IF NOT EXISTS admin_db;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'passwordForMySQL8.1';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
