server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false

    security:
        user:
          name: user
          password: password
        basic:
          enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
      routes:
        - id: attendance-service
          uri: http://attendance-service:8082
          predicates:
              - Path=/api/attendance/**
              - Method=OPTIONS,GET,POST
          filters:
            - RewritePath=/api/attendance/(?<segment>.*), /attendance/${segment}

        - id: auth-route
          uri: http://employee-service:8081
          predicates:
                  - Path=/api/auth/**
                  - Method=OPTIONS,GET,POST
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}
        - id: employee-route
          uri: http://employee-service:8081
          predicates:
                  - Path=/api/employee/**
                  - Method=OPTIONS,GET,POST
          filters:
          - RewritePath=/api/employee/(?<segment>.*), /employee/${segment}

        - id: employee-attendance-route
          uri: http://employee-service:8081
          predicates:
                  - Path=/api/employee-attendance/**
                  - Method=OPTIONS,GET,POST
          filters:
            - RewritePath=/api/employee-attendance/(?<segment>.*), /employee-attendance/${segment}

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

    # 선택: CORS 설정


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
jwt:
  secret: ekxRWm04M3g3c0JOKFJaOXJZdjVEQHVGYkp2M0hzSzIjbk12RXlQdHFBKjVmQjlrWHBXOQ==
  expiration: 3600000
